### ISSUE TITLE
Installation errors for Python 3.9.7, pip 21.2.3, macOS BigSur

### ISSUE THREAD

**Issue by druzmieres** [astropy/pyvo#297] opened 2022-02-04 12:59 UTC
Hi, 

I've found what seems to be an issue when installing pyvo in a new virtualenv.
```
Python version: 3.9.7
pip version: 21.2.3
OS: MacOS Big Sur 11.5.2
```
I'm running
```
$ pip install pyvo
```
And getting the following trace:
```
Collecting pyvo
  Using cached pyvo-1.2.1.tar.gz (840 kB)
    ERROR: Command errored out with exit status 1:
     command: /path/.env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/setup.py'"'"'; __file__='"'"'/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-pip-egg-info-y09cuob2
         cwd: /private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/
    Complete output (59 lines):
      ERROR: Command errored out with exit status 1:
       command: /path/.env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-wheel-0q4nb_vk/astropy-helpers_df02cfb067c54389b8e9ee2e9d3a6152/setup.py'"'"'; __file__='"'"'/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-wheel-0q4nb_vk/astropy-helpers_df02cfb067c54389b8e9ee2e9d3a6152/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-wheel-dgaff9k0
           cwd: /private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-wheel-0q4nb_vk/astropy-helpers_df02cfb067c54389b8e9ee2e9d3a6152/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for astropy-helpers
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/path/.env/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Users/fda/opt/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/path/.env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/tmpitgwwwk4', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/ah_bootstrap.py", line 556, in _do_download
        dist.fetch_build_eggs(req)
      File "/path/.env/lib/python3.9/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/path/.env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/path/.env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/path/.env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/path/.env/lib/python3.9/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/path/.env/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/path/.env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/tmpitgwwwk4', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/setup.py", line 8, in <module>
        import ah_bootstrap
      File "/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/ah_bootstrap.py", line 944, in <module>
        BOOTSTRAPPER = _Bootstrapper.main()
      File "/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/ah_bootstrap.py", line 263, in main
        bootstrapper.run()
      File "/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/ah_bootstrap.py", line 345, in run
        dist = method()
      File "/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/ah_bootstrap.py", line 413, in get_local_directory_dist
        upgrade = self._do_upgrade(dist)
      File "/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/ah_bootstrap.py", line 593, in _do_upgrade
        return self._do_download(version=upgrade.version)
      File "/private/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/pip-install-vr2im0o0/pyvo_5dbb98136ff447af9e88c6b50c6f5004/ah_bootstrap.py", line 578, in _do_download
        raise Exception(msg.format(DIST_NAME, source, repr(e)))
    Exception: Error retrieving astropy-helpers from PyPI:
    DistutilsError("Command '['/path/.env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/b_/0ynw9s8n5yngbksc080wgqp00000gn/T/tmpitgwwwk4', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.")
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5d/91/a75a7150b89dd3e030439f6a6a9b6e8ed2c4b5a433d9f1b88e0a27bbd418/pyvo-1.2.1.tar.gz#sha256=3630ad7c62acf9ce435a9b2d997376fa9fae6865ada6632735680c90ccf525e6 (from https://pypi.org/simple/pyvo/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyvo-1.2-py3-none-any.whl (832 kB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting astropy>=4.0
  Using cached astropy-5.0.1-cp39-cp39-macosx_10_9_x86_64.whl (6.9 MB)
Collecting numpy>=1.18
  Using cached numpy-1.22.2-cp39-cp39-macosx_10_14_x86_64.whl (17.6 MB)
Collecting pyerfa>=2.0
  Using cached pyerfa-2.0.0.1-cp39-cp39-macosx_10_9_x86_64.whl (340 kB)
Collecting PyYAML>=3.13
  Using cached PyYAML-6.0-cp39-cp39-macosx_10_9_x86_64.whl (197 kB)
Collecting packaging>=19.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.7-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 3.4 MB/s 
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.11-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Installing collected packages: pyparsing, numpy, urllib3, PyYAML, pyerfa, packaging, idna, charset-normalizer, certifi, requests, astropy, pyvo
Successfully installed PyYAML-6.0 astropy-5.0.1 certifi-2021.10.8 charset-normalizer-2.0.11 idna-3.3 numpy-1.22.2 packaging-21.3 pyerfa-2.0.0.1 pyparsing-3.0.7 pyvo-1.2 requests-2.27.1 urllib3-1.26.8
```

In the end it manages to install pyvo, but I don't think those exceptions should be there.

**Comment by neutrinoceros** [comment] 2022-02-04 20:25
Just to complete the report: pip first tries to install pivot 1.2.1 but fails, then falls back to 1.2, so, definitely something that shouldn't happen with recent versions of Python and pip as here.

**Comment by bsipocz** [comment] 2022-02-10 07:07
I'm closing this as a duplicate of #296 

Please `pip install wheel` as a workaround for now when building from source until we'll upload a whl to pypi for the latest release.

**Closed by bsipocz** 2022-02-10 07:07 UTC
