### ISSUE TITLE
unexpected parsing from AsyncTAPJob.fetch_result()

### ISSUE THREAD

**Issue by agy-why** [astropy/pyvo#237] opened 2020-09-04 13:31 UTC
# Context 

We host a TAP service https://www.plate-archive.org/query/ . The data base contains arrays of char of various length. Some of our users have issue fetching these.

# Problem

Fetching these data with sync job, returns a binary string of the correct length.
Fetching these data with async job, returns a binary of size 1. 

# Minimal example

```python
import pyvo as vo

name = 'applause'
url = "https://www.plate-archive.org/tap"
token = 'Token <your-token>'
print('TAP service {} \n'.format(name))

# Setup authorisation
tap_session = requests.Session()
tap_session.headers['Authorization'] = token
tap_service = vo.dal.TAPService(url, session=tap_session)

lang = "PostgreSQL"
query = """
SELECT p.date_orig, 
    FROM applause_dr3.plate AS p
    LIMIT 1
"""

tap_result = tap_service.run_sync(query, language=lang)
result = tap_result.to_table().to_pandas()
print(result['date_orig'][0])
```
This works and returns the expected data as an array of bytes of length 10.

replacing with 
```python
tap_result = tap_service.run_async(query, language=lang)
```
Fails. The results are an array of 1 byte. 

# Expected results

The sync and async job should return same results.

I thank you in advance.

**Comment by andamian** [comment] 2020-09-04 22:38
I've tried to reproduce it with a TAP service that I have credentials with (https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/argus) but I was not able. In both cases it came back with the same result.

I personally don't have an account with APPLAUSE but I'm willing to work with you to figure out what is wrong.
Instead of calling `run_async` you could call `tap_service.submit_job(query)`. The method returns a job in pending phase (`job.phase=PENDING`) which you can execute with method `job.run()`. After that check the phase again. If everything works fine, it should **eventually** (depending on the time it takes to run the query) move to `job.phase=COMPLETED` after which you can access the results with `job.fetch_results()`. That would be the success path that `run_async` is following.

Note that the result of the query is accessible from `job.job_uri` in case you want to access it by means other than pyvo (requests, curl etc). Just make sure you use the same credentials.

I hope this helps but please let me know if you can be of further help.

**Comment by andamian** [comment] 2020-09-05 00:13
No problem @agy-why - glad to be of help.

Indeed I've managed to create the account and reproduce the scenario you described. It turns out that the problem is in the description of the type of the column in `VOTable`. More specifically, the async end point returns that column as char as opposed to char array. Compare the description of VOTable from the `sync` end point:

`<FIELD ID="date_orig" **arraysize="10"** datatype="char" name="date_orig" ucd="time.epoch;obs.exposure"/>`

with the one from the `async` endpoint:

`<FIELD name="date_orig" ucd="time.epoch;obs.exposure" datatype="char" />`

That explains why it returns "1" (first character) in the result. Can you inform APPLAUSE maintainers to fix the type of the `date_orig` column in the async results?

I'm going to close this ticket for now but please let me know if I can be of further assistance.

Thanks for using `pyvo`

**Closed by andamian** 2020-09-05 00:13 UTC

**Comment by agy-why** [comment] 2020-09-05 07:43
Dear @andamian,

Thank you very much for this very fast and efficient help. 
This will greatly help us in finding the issue.

I thank you for your support and wish you a nice day,

Yori
