### ISSUE TITLE
PyVO cannot be installed into a clean Python environment

### ISSUE THREAD

**Issue by astrofrog** [astropy/pyvo#228] opened 2020-05-28 12:51 UTC
PyVO cannot currently be installed into a completely clean environment:

```
$ python -m venv ~/python/empty
$ source ~/python/empty/bin/activate
$ pip install pyvo
Collecting pyvo
  Downloading pyvo-1.0.tar.gz (776 kB)
     |████████████████████████████████| 776 kB 2.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/tom/python/empty/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2ydx9x1h/pyvo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2ydx9x1h/pyvo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-2ydx9x1h/pyvo/pip-egg-info
         cwd: /tmp/pip-install-2ydx9x1h/pyvo/
    Complete output (59 lines):
      ERROR: Command errored out with exit status 1:
       command: /home/tom/python/empty/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-fdm7e9ix/astropy-helpers/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-fdm7e9ix/astropy-helpers/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-u_cfnib_
           cwd: /tmp/pip-wheel-fdm7e9ix/astropy-helpers/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for astropy-helpers
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/tom/python/empty/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/tom/python/empty/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpj2f_omnq', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-2ydx9x1h/pyvo/ah_bootstrap.py", line 556, in _do_download
        dist.fetch_build_eggs(req)
      File "/home/tom/python/empty/lib/python3.8/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/tom/python/empty/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/tom/python/empty/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/tom/python/empty/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/tom/python/empty/lib/python3.8/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/tom/python/empty/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/tom/python/empty/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpj2f_omnq', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2ydx9x1h/pyvo/setup.py", line 8, in <module>
        import ah_bootstrap
      File "/tmp/pip-install-2ydx9x1h/pyvo/ah_bootstrap.py", line 944, in <module>
        BOOTSTRAPPER = _Bootstrapper.main()
      File "/tmp/pip-install-2ydx9x1h/pyvo/ah_bootstrap.py", line 263, in main
        bootstrapper.run()
      File "/tmp/pip-install-2ydx9x1h/pyvo/ah_bootstrap.py", line 345, in run
        dist = method()
      File "/tmp/pip-install-2ydx9x1h/pyvo/ah_bootstrap.py", line 413, in get_local_directory_dist
        upgrade = self._do_upgrade(dist)
      File "/tmp/pip-install-2ydx9x1h/pyvo/ah_bootstrap.py", line 593, in _do_upgrade
        return self._do_download(version=upgrade.version)
      File "/tmp/pip-install-2ydx9x1h/pyvo/ah_bootstrap.py", line 578, in _do_download
        raise Exception(msg.format(DIST_NAME, source, repr(e)))
    Exception: Error retrieving astropy-helpers from PyPI:
    DistutilsError("Command '['/home/tom/python/empty/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpj2f_omnq', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.")
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I'm not 100% sure what is causing this but the easiest fix would be to migrate the package away from using astropy-helpers as described in [this](https://docs.astropy.org/projects/package-template/en/latest/ape17.html) migration guide (we've already done this for most other packages in the astropy organization).

**Comment by astrofrog** [comment] 2020-05-28 12:56
Just to be clear, I know that installing ``wheel`` first would fix the issue - this is more a problem that comes up in some automated builds for other packages, e.g. reproject, which have PyVO as a dependency.

**Comment by cbanek** [comment] 2020-05-28 18:32
Thanks for bringing this up - I didn't even know migrating away from astropy-helpers was a thing.  To be honest, it's always caused a lot of confusion for me to get things working locally (mostly because I think my mind struggles with submodules), so I'm all for going through the guide and doing that.  Although @andamian  is talking about releasing pyvo in the very soon future for the sia2.  So I think we can do this first thing after that?

**Comment by cbanek** [comment] 2020-05-28 18:37
Just tried to do this myself, and I don't see an error, although I'm running python 3.7.5 and virtualenv... trying to install python3.8 and getting what you're doing to work on my system is making it confused, and I can't even make the env.

**Comment by astrofrog** [comment] 2020-05-29 11:19
@cbanek - I've just sent out an email about APE 17 and astropy-helpers, since indeed we hadn't advertised it too widely yet. Hope this clarifies things!

**Comment by astrofrog** [comment] 2020-05-29 15:11
Another quick solution to this for now would be to also publish the wheels for this package. Would it be possible to do this? (it should be easy since it's a pure-Python package?)

**Comment by odysseus9672** [comment] 2020-06-10 06:24
If the [versions of `pyvo` on  pip](https://pypi.org/project/pyvo/) requires the [`wheel` package](https://pypi.org/project/wheel/), why does pip not install the `wheel` package? I was able to install using the github source without having to install `wheel`, but this seems to be a bug in the versions of `pyvo` on pip.

**Comment by onekiloparsec** [comment] 2020-07-14 20:30
For those who are looking for a temporary hack in order to have their CI pass... here is the line I put in my `requirements.txt` file:

`-e git+https://github.com/astropy/pyvo.git@cfbd8f6a24d83f0ae9b0b6a61c30c66bf5d09d7e#egg=pyvo`

for v1.1.

**Comment by astrojuanlu** [comment] 2021-05-23 11:24
> Another quick solution to this for now would be to also publish the wheels for this package. Would it be possible to do this? (it should be easy since it's a pure-Python package?)

+1!

**Comment by Antrix9** [comment] 2021-05-27 07:00
Thanks for that suggestion of making wheel file itself and installing that, it worked

**Comment by bsipocz** [comment] 2021-06-02 07:25
I've also run into this issue during class with someone using a newish environment on windows (so `wheel` didn't get pulled in by another package). 
Having a bdist on pypi would provide a perfect workaround/fix.

**Comment by astrofrog** [comment] 2021-06-02 09:25
@cbanek @andamian - would one of you be able to build and upload a wheel to PyPI for the current latest release? This should not take long as you can just build a single pure Python wheel for all platforms. You can just do:

```
git checkout v1.1
python setup.py bdist_wheel
twine upload dist/*.whl
```

If neither of you has time, I notice that @eteq also has upload access for PyPI, so @eteq could you do this?

**Comment by andamian** [comment] 2021-06-02 14:38
I don't have access to the `pypi` credentials but I believe @cbanek can do it.

**Comment by tomdonaldson** [comment] 2021-06-03 16:11
> I don't have access to the `pypi` credentials but I believe @cbanek can do it.

@andamian, you and I should probably get access to those credentials.

**Comment by andamian** [comment] 2021-06-03 16:15
@tomdonaldson - with #247 any admin should be able to do it without explicit access to those credentials (they are available from the organization). I just need the time to do it.

**Comment by jpl-jengelke** [comment] 2021-06-05 02:04
This is a causing an install issue also for the citizens science project EXOTIC. 

I'd like to provide a bit more detail, though it's still a little fuzzy. Basically Pip has been upgraded to sort of focus on the PEP 517 standard which uses a TOML file. Previously, Pip would try to run `setup.py bdist_wheel` and if it failed it would fallback to `setup.py install`. With the TOML change, it now falls back to the `setup.py bdist_wheel` which of course doesn't work. PEP 518 specifies that apps should adopt a certain spec for builds to conform, but `PyVO` isn't updated for that. Confoundingly, the behavior may be different between platform builds, e.g. Mac, PC, etc., according to my testing. 

[There is a Pip issue to add an additional fallback option, but there seems to be some dispute on whether to implement it and it has been sitting for a year.](https://github.com/pypa/pip/issues/8302) 

Ideally, `PyVO` would [update its `setup.cfg`](https://github.com/astropy/pyvo/blob/dd3914e01333cb91681d118fdfc98f1bfc2a543d/setup.cfg#L43) to add `wheel` at least for the time being. [Here is the PR to do just that.](https://github.com/astropy/pyvo/pull/265)

**Comment by astrojuanlu** [comment] 2021-06-05 08:05
The short-term, tactical solution is still to upload a wheel to PyPI. It takes 5 minutes, but someone with PyPI access has to find the mental energy to allocate those 5 minutes :)

**Comment by astrofrog** [comment] 2021-06-05 10:22
@astrojuanlu - I agree and I even posted the commands here: https://github.com/astropy/pyvo/issues/228#issuecomment-852863667. I don't have access to PyPI unfortunately. It has to be @eteq or @cbanek

**Comment by bsipocz** [comment] 2021-06-05 19:43
We really should resolve that very long-lasting issue of revising access rights as the current situation is unsustainable and we overall spend an order of mag more time on not being able to resolve benign issues like this.

**Comment by eteq** [comment] 2021-06-07 13:24
Alright, I allocated those 5 minutes, as @astrojuanlu put it :wink: - see https://pypi.org/project/pyvo/#files

Not sure it that's enough for us to call this issue closed? (i.e., we've done the short term fix so the issue as stated is fixed - I checked and it now works.)

**Comment by eteq** [comment] 2021-06-07 13:27
Also on

> We really should resolve that very long-lasting issue of revising access rights 

Is there someone else who should have rights in pypi for pyvo? @cbanek has it I see but I could add whoever else makes sense from the maintainer team (if I recall correctly, the last time this came out the others weren't sure they *wanted* it :shrug: ).

**Comment by Antrix9** [comment] 2021-06-08 06:35
HOW TO SOLVE PyVO INSTALLATION PROBLEM --------------
STEP 1 :-  Go to Pyvo pylib website (https://pypi.org/project/pyvo/)
STEP 2 :- Go to download Files Options & download whl file 
Step 4: Extract Package, you just downloaded
Step 5 :- install using pip 
Step 7 : - Enjoy Coding :)

**Comment by astrojuanlu** [comment] 2021-06-08 06:45
Thanks a lot @eteq ! I was not joking 😅 I'm often overloaded with 5-minute chores and I'm out of mental energy to do them...

**Comment by Antrix9** [comment] 2021-06-08 07:58
> Thanks a lot for fixing this. @Antrix9 your solution is ok for local development, but hardly usable when PyVO is part of an automated deployment pipeline.

yep ik, but I just done my part (Hoping not too many ,but it may helps a few people )😇

**Comment by astrojuanlu** [comment] 2021-06-08 08:10
In any case, @onekiloparsec @Antrix9 this is not needed because `pip install pyvo` now works without `wheel` package installed. Proof:

<details>

```
$ python3.9 -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip list
Package       Version
------------- -------
pip           20.0.2 
pkg-resources 0.0.0  
setuptools    44.0.0 
(.venv) $ pip install pyvo --no-cache-dir
Collecting pyvo
  Downloading pyvo-1.1-py3-none-any.whl (802 kB)
     |████████████████████████████████| 802 kB 7.5 MB/s 
Collecting mimeparse
  Downloading mimeparse-0.1.3.tar.gz (4.4 kB)
Collecting astropy
  Downloading astropy-4.2.1-cp39-cp39-manylinux1_x86_64.whl (9.6 MB)
     |████████████████████████████████| 9.6 MB 776 kB/s 
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 10.3 MB/s 
Collecting numpy>=1.17
  Downloading numpy-1.20.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 281 kB/s 
Collecting pyerfa
  Downloading pyerfa-2.0.0-cp39-cp39-manylinux2010_x86_64.whl (742 kB)
     |████████████████████████████████| 742 kB 23.3 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
     |████████████████████████████████| 145 kB 17.6 MB/s 
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 9.8 MB/s 
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 20.1 MB/s 
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 75.5 MB/s 
Building wheels for collected packages: mimeparse
  Building wheel for mimeparse (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tn4hqme3/mimeparse/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tn4hqme3/mimeparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-k3ipvnva
       cwd: /tmp/pip-install-tn4hqme3/mimeparse/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for mimeparse
  Running setup.py clean for mimeparse
Failed to build mimeparse
Installing collected packages: mimeparse, numpy, pyerfa, astropy, certifi, urllib3, chardet, idna, requests, pyvo
    Running setup.py install for mimeparse ... done
Successfully installed astropy-4.2.1 certifi-2021.5.30 chardet-4.0.0 idna-2.10 mimeparse-0.1.3 numpy-1.20.3 pyerfa-2.0.0 pyvo-1.1 requests-2.25.1 urllib3-1.26.5
```

Good luck complaining for the lack of mimeparse wheels 😉 last released in 2013. In any case, now the installation works!
</details>

**Comment by astrojuanlu** [comment] 2021-06-08 08:37
What do you mean @onekiloparsec ? The `pip install pyvo` works now, the error message is unrelated and pip succeeds in building the wheel of `mimeparse` anyway (`Successfully installed astropy-4.2.1 certifi-2021.5.30 chardet-4.0.0 idna-2.10 mimeparse-0.1.3 numpy-1.20.3 pyerfa-2.0.0 pyvo-1.1 requests-2.25.1 urllib3-1.26.5`). For the developers, you are right that it will be more sustainable if wheels get published automatically.

The title of the issue is "PyVO cannot be installed into a clean Python environment", this has been effectively solved for users. Now, pyvo developers might want to find a way to avoid this manual process in the future, but that's an entirely different topic. I vote to close this issue.

**Comment by onekiloparsec** [comment] 2021-06-08 08:44
My remark was a simple reaction to the "it works on my machine" feeling I had when reading the comment. 

Again, thanks for fixing this. I agree the ticket as such can be closed. I'll test and confirm the success of the automatic deployment on my side.

**Comment by tomdonaldson** [comment] 2021-06-09 13:22
I'm closing this since `pip install pyvo` now works as expected.  The discussion about improving this process moving forward will be covered in #247.

Thanks to everyone who helped with this!

**Closed by tomdonaldson** 2021-06-09 13:22 UTC
Labels: bug
