### ISSUE TITLE
support for full-url semantics no longer provided, breaking existing code

### ISSUE THREAD

**Issue by almicol** [astropy/pyvo#298] opened 2022-02-09 12:47 UTC
At ESO we publicised the usage of pyvo, and provided jupyter notebooks to our community showing examples on how to programmatically  access the ESO archive. 
One important feature is the ability to address a particular record in a datalink response using its semantics, e.g.:
`
semantics = 'http://archive.eso.org/rdf/datalink/eso#calSelector_raw2master'
raw2master_url = next(datalink.bysemantics( semantics )).access_url
`

That code worked nicely with pyvo v1.1; with a later version of pyvo (we tried with v1.2.1) it does no longer work.
 
The comment in the current github code (adhoc.py) reads:
`semantics: str or list
            One or more term(s) from the datalink vocabulary
            (http://www.ivoa.net/rdf/datalink/core).  Terms may be
            passed in with or without a leading hash.  Note that at
            this point non-datalink/core URIs (i.e., full resource
            URIs) are not supported (and will be butchered).`

That comment, not present in pyvo v1.1, explains why the ESO code no longer works, as 
the semantics above is a full resource URI (it cannot be changed to a term from the core vocabulary).

So, at this point our beloved pyvo module is no longer compliant with the datalink ivoa standard, as the standard still foresees non-core, full resource URIs. 

Even worse: any script that our ESO user community would have developed in the meantime would break.
There are some instrument operation teams using that functionality. So the impact of this is not minor on us.

May I please ask you to provide a workaround?
Can I also please ask you to re-instantiate the support for full URIs, so to be compliant to the standard?

Many thanks in advance!

**Comment by msdemlei** [comment] 2022-02-09 16:55
On Wed, Feb 09, 2022 at 04:47:26AM -0800, almicol wrote:
> At ESO we publicised the usage of pyvo, and provided jupyter notebooks to our community showing examples on how to programmatically  access the ESO archive. 
> One important feature is the ability to address a particular record in a datalink response using its semantics, e.g.:
> `
> semantics = 'http://archive.eso.org/rdf/datalink/eso#calSelector_raw2master'
> raw2master_url = next(datalink.bysemantics( semantics )).access_url
> `
> 
> That code worked nicely with pyvo v1.1; with a later version of pyvo (we tried with v1.2.1) it does no longer work.

Oh, dang.  Apologies.  I had underestimated the extent to which
people used custom semantics terms.  In my defense, I should say none
of these custom terms were ever discussed or even mentioned on the
semantics list.

> May I please ask you to provide a workaround?

I suppose you could use '#calSelector_raw2master' without the URL
prefix, but you really shouldn't; that would then break later code.
I'm afraid the best workaround for now would be to warn people that
this is broken in a number of releases of pyVO.

Since this is an actual regression, I wonder if we can backport the
change to whatever stable release we have, once we have ascertained
it does fix your problem.

> Can I also please ask you to re-instantiate the support for full
> URIs, so to be compliant to the standard?

PR #299 should fix it -- could you try it out?

After this, can I mount a soap box for a second? You see, what you do
with the semantics column here looks fairly wrong from the outside.
The purpose of semantics is to give machines a rough idea of what a
link is, *across data providers* ("interoperably").  If you want a
secret handshake between your service and custom code specifically
written for your archive, either use a custom datalink column, or
have a tag within the text in the description column, or have the
custom code inspect the access_url, or whatever.

The most straightforward use of semantics is to let a client organise
the links hierarchically without any further contract with the data
provider, as, e.g., http://dc.g-vo.org/shomydl/q/f/form does.
Putting any old URL into semantics breaks this. 

You may now say: "Well, why do you let me do it then?".   Well,
that's a consequence of the remote hope that we could infer
hierarchical relationships across vocabularies, a hope many still
held when datalink was written.

I don't think anyone expects we'll ever actually have clients that
will try to retrieve vocabulary fragments from random places on the
internet, for a whole host of reasons; and even if one client did
that right, expecting all clients to correctly deal with that is
asking for either no or broken implementations.

So -- please don't use custom URLs in datalink's semantics column any
more.  If your terms are usable across providers, please write a VEP.
If they are not, what you really want is a secret handshake between
you and code specifically written for your service; and in that case,
please use something not designed to be interoperable (see above).

**Comment by almicol** [comment] 2022-02-10 11:47
Hi Markus, thanks for taking care of it. We badly need this fix.

Thanks also for mounting a soap box, though I have to say that I cannot grab the soap, it's too slippery.

<soap bubble>
What matters is not how I use the standard, but that fact that the current version of pyvo does not support the current version of the datalink standard.

The fact is that the datalink standard is a standard because it was discussed at length within the IVOA community. Abandoning or changing the agreed behaviour would require new discussions and a new version of the standard (indeed in the making, see below). If the intended usage of the standard was something different from what I'm using, that should have been clarified in the standard. 
The standard states: _"The semantics column is intended to be machine-readable and assist automating data retrieval and processing."_ and this is exactly how I am using it.

And it also states: _"Services are encouraged to use the core vocabulary as much as possible, but may use a custom vocabulary as long as they use a custom vocabulary namespace (base URI); the base URI should be resolvable to a human-readable document describing the terms."_ 
which I fully understand and share, and indeed our datalink mostly uses the core datalink vocabulary; though, there are 6 ESO-specific things not covered by the core vocabulary, and for which we had to invent our own semantics, and I duly did what described in the standard (the URI resolves into a readable page).

We did not want to have secret handshakes, we want something that ESO users can easily see and understand how to use. 
We did not want to have an extra column, as those 6 things are extra records, not an extra columns, in the datalink table response.
Using one single method (bysemantics) to identify the different records is the simplest thing to do.

The standard does not say that I have to write a VEP (I do not even know what VEP is, nor obviously I'd  know how to create one). Nor I would want to do that, as all I need is a simple mechanism to provide a very ESO-specific service specifically to a member of the ESO community. A generic, ESO-unaware, VO user would not know what to do with the response from such a service. 

I guess other institutes have similar needs.
Allowing the various data providers to easily extend the vocabulary is as simple as it is powerful: one and the same software library can be used to serve both the VO community at large, and the data provider's specific community (ESO's in my case), without having to change a single line of code!

I just saw a draft for a new version of the datalink standard, and see that indeed the idea there is to drop the full URIs. I will have to go back to the IVOA and have that fully discussed, for the reasons mentioned above. So I guess we will argue about the future of datalink within the IVOA :) 

BTW, regarding the future: can I request to add some new terms in the core vocabulary? That I would know how to do; would that help? 

So much for the soap...
</soap bubble>

Back to this specific github issue:
As said, for ESO is very important to have this fixed urgently (and this statement comes actually not from me, but from the boss of my boss ;) ). 

In the meantime I'm putting some alerts for our users, asking them to use pyvo v1.1, and to not upgrade until this issue is, hopefully, resolved. I hope you can easily do that.

Thanks again Markus, pyvo is not only great, but an essential piece of software for our community!

**Comment by msdemlei** [comment] 2022-02-10 12:47
On Thu, Feb 10, 2022 at 03:47:44AM -0800, almicol wrote:
> Hi Markus, thanks for taking care of it. We badly need this fix.

Have you tried it and made sure it fixes your issue?  If so, I'd try
to get it merged and released as fast as possible, but I'd need your
green light.

> Thanks also for mounting a soap box, though I have to say that I
> cannot grab the soap, it's too slippery.

:-) Well, this discussion really shouldn't happen in a github
issue but on the DAL mailing list; feel free to open it there.

Meanwhile:

> which I fully understand and share, and indeed our datalink mostly
> uses the core datalink vocabulary; though, there are 6 ESO-specific
> things not covered by the core vocabulary, and for which we had to
> invent our own semantics, and I duly did what described in the
> standard (the URI resolves into a readable page).

...which clearly wouldn't be enough to enable the hierarchical
presentation of the links, nor would they let a client work out title
and description for some term.  Which makes the semantics column not
very useful.

You're right that the standard allows you to put in full URIs there.
But that doesn't mean it's a good thing to do so, and the reasons for
those only became apparent as we gained experience with vocabularies.
Remember, Datalink is now seven years old, and it was actually the
first standard to experiment with this kind of thing.  And it actually
took us until last year to give the tech behind the semantics column
a solid foundation in Vocabularies 2.

So... standards and their practices live.  I appreciate that
sometimes sucks for adopters, but this stuff *is* hard, and far too
few people actually help thinking out things in the VO.  It's a
miracle that things actually work as well as they do.

> We did not want to have secret handshakes, we want something that
> ESO users can easily see and understand how to use.  We did not
> want to have an extra column, as those 6 things are extra records,
> not an extra columns, in the datalink table response.  Using one
> single method (bysemantics) to identify the different records is
> the simplest thing to do.

I cannot comment on the concrete cases, as I don't know them; my
initial comment was mainly: "If it's a contract between ESO's servers
and ESO's clients that does not apply anywhere else, then perhaps
shouldn't use something intended to be interoperable".  But I give
you that's not helpful in itself; I could probably say a bit more if
I understood what you actually want to do.

> The standard does not say that I have to write a VEP (I do not even
> know what VEP is, nor obviously I'd  know how to create one). Nor I

No, that's because it's so much older than the VEP process.  The
pertinent link is on the vocabulary page,
https://www.ivoa.net/rdf/datalink, though perhaps not terribly
conspicuous (at the very bottom).  If you have suggestions on how to
make this a bit more discoverable, I'm happy to hear them.

> would want to do that, as all I need is a simple mechanism to
> provide a very ESO-specific service specifically to a member of the
> ESO community. A generic, ESO-unaware, VO user would not know what
> to do with the response from such a service. 

Right -- that's why my first reaction was to suggest an ESO-specific
extension rather than using something designed for interoperable
services.  But as I said: Since I don't know your concrete case I
can't say whether or not that was appropriate advice.

> Allowing the various data providers to easily extend the vocabulary
> is as simple as it is powerful: one and the same software library
> can be used to serve both the VO community at large, and the data
> provider's specific community (ESO's in my case), without having to
> change a single line of code!

Perhaps -- but then every data provider will create their own terms,
and the same concept will have different identifiers on different
services, making clients' lives suck.  It's always a question who
does the work of mapping different things, and the idea of
interoperable services is to take it off of the shoulders of users as
much as possible.  Of course, that's at the expense the data
providers, who are then forced to talk to each other and come up with
agreements.  In this case: on what to label certain classes of items
coming with a dataset.

[I should mention that of course the data providers greatly profit
from being interoperable, too, e.g., by being able to offer all the
great interoperable clients to their users, or by not having to
re-invent too many wheels.  But the initial investment and the need to
have lengthy discussions where you could otherwise just start
implementing *are* a cost]

> BTW, regarding the future: can I request to add some new terms in
> the core vocabulary? That I would know how to do; would that help? 

Sure.  Just post your ideas to the semantics mailing list.  We'll
guide you from there.  You could also read the Vocabularies standard,
but, sure enough, in that particular field the world is currently
moving, too (from volute to github -- sigh), so at this point just
posting to semantics is the way to go.

Anyway: Let's take all of this to IVOA mailing lists -- it's not very
much connected to pyVO, and it has no place in a github issue anyway.

**Closed** 2022-02-15 21:37 UTC
