### ISSUE TITLE
pyvo.dal.exceptions.DALFormatError: ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by xyz3919** [astropy/pyvo#162] opened 2019-08-09 17:50 UTC
I was trying to use the pivo.dal to query DES DR1 images, but I got into the problem.
The code I ran:

```
import pyvo
from pyvo.dal import sia
DEF_ACCESS_URL = "http://datalab.noao.edu/sia/des_dr1"
svc = sia.SIAService(DEF_ACCESS_URL)
imgTable = svc.search((0.0132, 1.253), size=0.001)
```

And it returned:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvo/dal/query.py", line 234, in execute_votable
    return votableparse(self.execute_stream().read)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvo/utils/decorators.py", line 10, in wrapper
    raw = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvo/dal/query.py", line 188, in execute_stream
    r = self.submit()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvo/dal/query.py", line 205, in submit
    r = s.get(url, params=params, stream=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvo/dal/sia.py", line 258, in search
    pos, size, format, intersect, verbosity, **keywords).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvo/dal/sia.py", line 572, in execute
    return SIAResults(self.execute_votable(), url=self.queryurl)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvo/dal/query.py", line 237, in execute_votable
    raise DALFormatError(e, self.queryurl)
pyvo.dal.exceptions.DALFormatError: ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```

I was wondering if this is something to do with the server or my pyvo package.
My pyvo version: 0.9.3

**Comment by xyz3919** [comment] 2019-08-09 19:48
I found that if I switch to python2. It worked.

**Comment by cbanek** [comment] 2019-08-09 21:29
Thanks for reporting this.  Usually if there's a connection error, or connection aborted, or connection reset by peer, it means that it's a networking issue between the client (pyvo) and the service, and usually the service is the one hanging up on you.

Taking your example code, I am able to reproduce the issue, but sadly I still don't know why.  I also concur that the same code works for python 2.7.  

If I change the URL of the datalab to be https instead of http, it seems like python3 does return the same result (empty table).  In the example you've given, do you think that there should be results returned or does it behave as you would expect with python 2?

When running the latest from master, it does seem to work with python 3.  I'm guessing something might have been fixed between 0.9.3 and then (which has been a fair number of changes) that fixed this?

Thanks again for reporting this as it is very important, because we want to deprecate the python 2 parts, so if something is different in python 3 and breaking something, I'd rather fix it.  I think some of the http networking between the two python versions is very different, although I'm not an expert in that!

**Comment by xyz3919** [comment] 2019-08-09 23:47
Thanks for checking ! 
For this query in python3, I expect to see the empty table as I got in python 2.
The url I used is from one of the examples in NOAO datalab jupiter notebook. After changing from "http" to "https", everything worked fine. I guess I would go for "https" instead of "http".

**Comment by cbanek** [comment] 2019-08-10 02:55
I'm also looking into if there are any outstanding network issues with datalab, as I work in the same building.  It looks like I had some interesting network blips that might be related.  I'll let you know!  I think HTTPS is probably safer anyway!

**Comment by cbanek** [comment] 2019-09-20 23:34
Going to close this out as it was a transient network issue, not a pyvo code issue

**Closed** 2019-09-20 23:34 UTC
