### ISSUE TITLE
Handle 'format' TAP parameter

### ISSUE THREAD

**Issue by jcsegovia** [astropy/pyvo#186] opened 2019-10-17 12:37 UTC
TAP specification allows the user to request results in a specific format.

'format' ('response_format' in v1.1) parameter is ignored and PyVo always tries to parse the results to convert them into a VOTable.

It would be useful to avoid translations of results in memory (performance issue: it is not optimal if we have to retrieve the results in VOTable and translate them into the requested format in memory).

**Comment by andamian** [comment] 2019-10-17 15:44
duplicate of #149

**Comment by jcsegovia** [comment] 2019-10-21 07:12
Yes. 'format' and 'responseformat' are already requested in #149 
I think we can close this issue.

**Closed** 2019-11-13 00:57 UTC
Labels: duplicate
